function [q] = euler2q(euler)
    
    q(1) = cos(euler(1)/2) * cos(euler(2)/2) * cos(euler(3)/2) + ...
           sin(euler(1)/2) * sin(euler(2)/2) * sin(euler(3)/2);
    q(2) = sin(euler(1)/2) * cos(euler(2)/2) * cos(euler(3)/2) - ...
           cos(euler(1)/2) * sin(euler(2)/2) * sin(euler(3)/2);
    q(3) = cos(euler(1)/2) * sin(euler(2)/2) * cos(euler(3)/2) + ...
           sin(euler(1)/2) * cos(euler(2)/2) * sin(euler(3)/2);
    q(4) = cos(euler(1)/2) * cos(euler(2)/2) * sin(euler(3)/2) - ...
           sin(euler(1)/2) * sin(euler(2)/2) * cos(euler(3)/2);
end